services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: multistack
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./docker:/docker-entrypoint-initdb.d
    adminer:
        image: adminer
        restart: on-failure
        ports:
            - 8080:8080
volumes:
    db_data: